package com.parse.starter;

/**
 * This class is the data object for holding one place.
 */
public class Place {

    private int id;
    private String name;
    private String address;
    private String logo;
    private double grade;
    private boolean openJobs;

    /**
     *
     * @param id the id of the place (will be generated by the server)
     * @param  name the name of the place
     * @param address the address of the place (in the future gps support;
     * @param grade the final grade calculated by the server
     */
    public Place (int id, String name, String address, double grade) {
        this.id = id;
        this.name = name;
        this.address = address;
        this.grade = grade;
        openJobs = false;
    }

    public Place (int id, String name, String address, double grade, boolean openJobs) {
        this(id, name, address, grade);
        this.openJobs = openJobs;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }


    public double getGrade() {
        return grade;
    }

    public void setGrade(double grade) {
        this.grade = grade;
    }
}
